
# Comment:

# Pobieranie ubuntu
FROM ubuntu: latest

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install g++

#Pobieranie repozytorium z git hub
RUN git clone https://github.com/NequLW/Lab7.git

#Tworzenie pliku typu executable
RUN g++ -o world lab7/main.cpp

#Urochomienie pliku z aplikacji w image
CMD Lab7/world